title: Train BetaVO-VAE / 3DShapes

device: &device cuda:0
parallel: false

task:
  object: train_vovae

data:
  train:
    name: shape3d
    root: data/3dshapes
    mode: train
  val:
    name: shape3d
    root: data/3dshapes
    mode: val

model:
  name: VOVAE
  latent: 6
  img_size: [3, 64, 64]
  beta: 6.0
  latent_vec_dim: 128
  orth_coef: 0.1

hyperparameters:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 100
  batch_size: 32
  loss_fn: ELBO

save:
  name: betavo_vae.3dshapes
  weights_path: saved/weights
  loss_path: saved/loss