title: Train VAE / 3DShapes

device: &device cuda:0
parallel: false

task:
  object: train_vae

data:
  train:
    name: shape3d
    root: data/3dshapes.h5
    mode: train
  val:
    name: shape3d
    root: data/3dshapes.h5
    mode: val

model:
  name: VAE
  latent: 6
  img_size: [3, 64, 64]
  beta: 1.0 # Vanila VAE

hyperparameters:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 100
  batch_size: 32
  loss_fn: ELBO

save:
  name: vae.3shapes
  weights_path: saved/weights
  loss_path: saved/loss